server:
  http2:
    enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres?sslmode=require'
    username: postgres.umndbnimuswczlydijnf
    password: FTSDq@5&v@Z&67T
  jpa:
    hibernate:
      ddl-auto: update

    # Add this so Hibernate knows which Dialect to use without probing
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jta:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${supabase.jwtSecret}

springdoc:
  show-actuator: true

# application.yml
langchain4j:
  open-ai:
    chat-model:
      api-key: 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
  task-planner-agent:
    name: TaskPlannerAgent
    description: 'Can plan tasks for a user given details about a goal.'
  task-creator-agent:
    name: TaskCreatorAgent
    description: 'Can create tasks for a user given details about the task from the task planner.'

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework: INFO
    com.optimal.backend.springboot: INFO

## Supabase Configuration
supabase:
  url: https://umndbnimuswczlydijnf.supabase.co
  anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbmRibmltdXN3Y3pseWRpam5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDUzMTQsImV4cCI6MjA2NzMyMTMxNH0.CL7UownGSH8e9XIsKz-5z2-iyUvZ3Ko4rwDaZzNfK-I
  jwtSecret: Cbcm2FHnRGZPrEAWVt4Ukfm3dHS1cAyokVSkik9ZEDxbMtEVnTfJLIWdFogttFiEXQOt83pPehKtTZscXQodIg==

swagger:
  contact-name: Optimal AI
  contact-mail: optimal.ai.app@gmail.com
  contact-url: https://optimal.ai
  app-name: Optimal.ai
  app-description: 'Optimal.ai is a project that helps you to achieve your goals.'
  app-version: 1.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
